feat: add new sdk method to update instance home credentials
IBM/ibm-iae-node-sdk pull request #52
Opened 2023-03-14 12:22 UTC by silpidhua

add new sdk method to update instance home credentials.

## PR summary

**Fixes:** <! -- link to issue -->

## PR Checklist
Please make sure that your PR fulfills the following requirements:
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

2023-03-14 12:23 UTC, silpidhua commented
Unit test
```
npm run test-unit

> iaesdk@2.2.0 test-unit
> npm run build && jest test/unit/


> iaesdk@2.2.0 build
> tsc && cp package.json dist/

 PASS  test/unit/common.test.js
 PASS  test/unit/ibm-analytics-engine-api.v2.test.js
 PASS  test/unit/ibm-analytics-engine-api.v3.test.js
--------------------------|---------|----------|---------|---------|-------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------|---------|----------|---------|---------|-------------------
All files                 |   99.79 |    93.05 |     100 |   99.79 |                   
 ibm-analytics-engine-api |   99.78 |    93.05 |     100 |   99.78 |                   
  v2.ts                   |   99.41 |    90.62 |     100 |    99.4 | 116               
  v3.ts                   |     100 |       95 |     100 |     100 | 100,1435          
 lib                      |     100 |      100 |     100 |     100 |                   
  common.ts               |     100 |      100 |     100 |     100 |                   
--------------------------|---------|----------|---------|---------|-------------------

Test Suites: 3 passed, 3 total
Tests:       150 passed, 150 total
Snapshots:   0 total
Time:        2.173 s
Ran all test suites matching /test\/unit\//i.
```

Integration test
```
npm run test-integration

> iaesdk@2.2.0 test-integration
> npm run build && jest test/integration


> iaesdk@2.2.0 build
> tsc && cp package.json dist/

 PASS  test/integration/ibm-analytics-engine-api.v3.test.js (21.828 s)
--------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                             
--------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------
All files                 |   66.53 |    30.55 |   62.71 |   66.39 |                                                                                                               
 auth                     |     100 |      100 |    12.5 |     100 |                                                                                                               
  index.ts                |     100 |      100 |    12.5 |     100 |                                                                                                               
 ibm-analytics-engine-api |   65.18 |    30.55 |      70 |   65.03 |                                                                                                               
  v2.ts                   |   18.82 |    28.12 |      30 |   18.34 | 58-89,111-135,157-193,215-251,272-315,335-371,391-428,460-499,519-555,576-618,636-672,688-717,738-781         
  v3.ts                   |   91.36 |     32.5 |   96.66 |   91.33 | 55,84,104,132,184,257,328,387,441,498,553,606,666,727,785,840,889,948,1003,1063,1125,1182,1244,1297,1350,1403 
 lib                      |     100 |      100 |     100 |     100 |                                                                                                               
  common.ts               |     100 |      100 |     100 |     100 |                                                                                                               
--------------------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------

Test Suites: 1 skipped, 1 passed, 1 of 2 total
Tests:       13 skipped, 24 passed, 37 total
Snapshots:   0 total
Time:        22.293 s, estimated 23 s
Ran all test suites matching /test\/integration/i.
```

2023-03-23 08:19 UTC, subinpc requested changes

2023-03-23 08:19 UTC, subinpc commented on .travis.yml
> +group: beta
Can you remove this?

2023-03-23 09:02 UTC, subinpc approved these changes

2023-03-23 09:03 UTC, merged

2023-03-23 09:05 UTC, Surya-Penumatcha commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/iaesdk/v/2.3.0)
- [GitHub release](https://github.com/IBM/ibm-iae-node-sdk/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: